name: iris_pic_editor
description: A image editor package.
version: 0.0.5+7
homepage: https://iris.ir

environment:
  sdk: ">=2.18.0"
  flutter: ">=2.2.0"

  # use this: https://pub.dev/packages/bitmap
  # use this: https://github.com/chooyan-eng/crop_your_image

dependencies:
  flutter:
    sdk: flutter

  image: ^4.0.10                 #      {crop, rotate}
  image_editor: ^1.3.0           # noWeb    {crop, rotate [native]}
  #image_editor_pro

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
